version: '3.8'

services:
  minio:
    image: nexus.fitcycle.online/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data
    env_file:
      - .env-minio
    command: server /data --console-address ":9001"


  postgres:
    image: nexus.fitcycle.online/postgres
    container_name: postgres
    restart: on-failure
    env_file: .env-postgres
    healthcheck:
      test: pg_isready -d fit
      interval: 5s
      timeout: 33s
      retries: 3
      start_period: 5s
    volumes:
      - ./dbdata:/var/lib/postgresql/data

  keycloak:
      build:
        image: nexus.fitycle.online/keycloak
      container_name: keycloak
      command: [ "start", "--db", "postgres", "--hostname-strict-https", "false",  "--hostname-strict", "false",  "--proxy", "edge", "--http-enabled", "true", "--import-realm",  "--spi-user-profile-legacy-user-profile-read-only-attributes", "*_RES_ACCESS_MODE" ]
      env_file: .env-keycloak
      ports:
        - 8080:8080
      depends_on:
        postgres:
          condition: service_healthy

  rabbitmq:
    image: nexus.fitcycle.online/rabbit
    container_name: rabbitmq
    env_file: .env-keycloak
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  dbdata:
    driver: local
  minio_data:
    driver: local
