server:
  port: 8082

api-prefix: /api/files
stage: ${STAGE_NAME:stage}

spring:
  application:
    name: myfit-files

  security:
    oauth2:
      resourceserver:
        jwt.issuer-uri: ${ISSUER_URI:http://localhost:8080/realms/myfit}

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:fit}
    password: ${RABBITMQ_DEFAULT_PASS:pw}

  cloud:
    openfeign:
      client:
        config:
          myfit-back:
            url: ${myfit-back.url}
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: ${api-prefix}/swagger-ui
    enabled: ${SWAGGER_ENABLE:true}
  api-docs:
    enabled: ${SWAGGER_ENABLE:true}

cors:
    url: ${CORS_URL:http://localhost:3000}

myfit-back:
  url: ${MYFIT_BACK_URL:http://127.0.0.1:80}
  username: ${MYFIT_BACK_USER:user}
  password: ${MYFIT_BACK_PASSWORD:password}

minio:
  url: ${MINIO_URL:http://127.0.0.1:9000}
  access-key: ${MINIO_ACCESS_KEY:fit}
  secret-key: ${MINIO_SECRET_KEY:miniopassword}
  bucket-name: ${MINIO_BUCKET_NAME:fitcycle}
  public-folder: public


queue:
  exercise:
    imageToConvert: files_files_exercise_image
    imageToSave: files_back_exercise_image

image-size:
  exercise:
    mobile:
      width: 200
      height: 300
    desktop:
      width: 600
      height: 900

tuz:
  username: ${TUZ_USER:tuz}
  password: ${TUZ_PASSWORD:password}
