spring:
  application:
    name: myfit-files

minio:
  url: http://127.0.0.1:9000
  access-key: admin
  secret-key: admin123
  bucket-name: minio1

logging:
  config: classpath:log4j2.xml
  level:
    root: info
    # org.springframework: DEBUG
