server:
  port: 8082

spring:
  application:
    name: myfit-files

  security:
    oauth2:
      resourceserver:
        jwt.issuer-uri: ${ISSUER_URI:http://localhost:8080/realms/myfit}
  datasource:
      driver-class-name: org.postgresql.Driver
      url: ${DB_URL:jdbc:postgresql://localhost:5432/app}
      username: ${DB_USER:app}
      password: ${DB_PASSWORD:pass}

cors:
    url: ${CORS_URL:http://localhost:3000}

keycloak:
    url: http://localhost:8080
    realm: master
    username: admin
    password: pw
    client-id: admin-cli

minio:
    url: http://127.0.0.1:9000
    access-key: admin
    secret-key: admin123
    bucket-name: minio1

#  spring:
#    security:
#      oauth2:
#        resourceserver:
#          jwt:
#            jwk-set-uri: http://localhost:8080/realms/myfit/protocol/openid-connect/certs
#
