name: deploy-dev
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup-jdk
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          server-id: github
          server-username: PACKAGE_USERNAME
          server-password: PACKAGE_PASSWORD
      - name: cache-maven-repo
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: build image
        run: mvn spring-boot:build-image
        env:
          PACKAGE_USERNAME: ${{ secrets.PACKAGE_USERNAME }}
          PACKAGE_PASSWORD: ${{ secrets.PACKAGE_TOKEN }}
      - name: extract version
        id: version-extractor
        uses: dostonhamrakulov/maven-artifact-version-extractor@v1.0
        with:
          file_path: ${{ github.workspace }}/pom.xml
      - name: docker login
        uses: docker/login-action@v3
        with:
          registry: nexus.fitcycle.online
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: docker push
        run: docker push nexus.fitcycle.online/myfit:${{ steps.version-extractor.outputs.version }}
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
      - run: kubectl apply -f k3s/stage-deployment.yml